### ISSUE TITLE
不知道为什么出现下面的问题

### ISSUE THREAD

**Issue by youfbi008** [amazeui/react-starter-kit#2]
执行 npm install；

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\DevelopPros\\nodejs\\\\node.exe" "D:\\DevelopPros\\nodejs\\no
de_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: amazeui-react@'>=1.0.0 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-alpha3","1.0.0-beta1"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\reacttest\react-starter-kit-master\npm-debug.log

**Comment by Minwe** [comment]
打开项目根目录下面的 `package.json`，改一下依赖的版本号：

```js
"amazeui-react": "^1.0.0"
```

改为：

```js
"amazeui-react": "*"
```

**Comment by youfbi008** [comment]
原来还有这样的即决办法 非常感谢

**Comment by Minwe** [comment]
没在 npm `2.x` 下测试过，有点小问题， 已经修复 f73f40b7cd50a7c00754564712d33f35edfa73e9
