### ISSUE TITLE
gulp.watch的疑问

### ISSUE THREAD

**Issue by msdlisper** [amazeui/react-starter-kit#4]
我发现gulpfile.js里的watch为
<pre>
gulp.task('watch', function() {
   gulp.watch('app/**/*.html', ['html']);
   gulp.watch('app/less/**/*less', ['styles']);
   gulp.watch('app/i/**/*', ['images']);
 });
</pre>
这里面并没有监视JS文件的改动,但我改了下app/js/Page/Index.js的内容,浏览器还是把改动刷新加载了
是什么原因呢...
我才开始用gulp,原谅我比较小白

**Comment by Minwe** [comment]
https://github.com/amazeui/react-starter-kit/blob/master/gulpfile.js#L168

**Comment by msdlisper** [comment]
那一行代码监视的是dist/目录下的文件,而我改的是app/js/Page里的文件啊,是哪里在监视呢

**Comment by Minwe** [comment]
https://github.com/amazeui/react-starter-kit/blob/master/gulpfile.js#L133

用的 watchify。
