### ISSUE TITLE
nam install error

### ISSUE THREAD

**Issue by fivevbear** [amazeui/react-starter-kit#8]
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0

npm ERR! shasum check failed for /var/folders/h_/bxtyx5q92mbf8jjg756nzjn80000gn/T/npm-21987-90b93f66/registry.npmjs.org/amazeui/-/amazeui-2.5.2.tgz
npm ERR! Expected: 7c24850c0a20dc170a5fbef7a7561945e7e32e23
npm ERR! Actual:   e0314fa2be75ee3a37ac3d6b863b114a433ef9c2
npm ERR! From:     https://registry.npmjs.org/amazeui/-/amazeui-2.5.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxx/WebstormProjects/react-starter-kit/npm-debug.log

**Comment by minwe** [comment]
`nam` 是个什么玩意？提 issue 之前应该保证 issue 本身没有问题。

上面提供的日志片段并没有什么有价值的信息。你可以尝试使用 Node 4.4 + NPM 2.x 的组合，现在有些包在 npm 3 中会有问题。

**Comment by Jerry-Lau** [comment]
nam, haha, xiaosidiele
